# Start from the latest golang base image
FROM pandoc/core:latest

# Install Pandoc and LaTeX
RUN apk --no-cache add texlive-xetex

# Add Maintainer Info
LABEL maintainer="colton.shaw@mattermost.com"
LABEL org.opencontainers.image.title="mmhealth"
LABEL org.opencontainers.image.description="Mattermost Healthcheck Image"
LABEL org.opencontainers.image.authors="Colton Shaw"
LABEL org.opencontainers.image.source="https://github.com/coltoneshaw/mmhealth"
LABEL org.opencontainers.image.licenses=MIT

RUN mkdir /files

# Set the Current Working Directory inside the container
WORKDIR /app

COPY ./template.tex .

ENTRYPOINT ["pandoc"]
